apps/multi_track_listening/lib/multi_track_listening_web/router.ex
defmodule MultiTrackListeningWeb.Router do
  use MultiTrackListeningWeb, :router
  use Pow.Phoenix.Router
  use Pow.Extension.Phoenix.Router, otp_app: :multi_track_listening

  alias MultiTrackListeningWeb.Plugs.{RedirectToPublishedMix, LoadMix}

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler
  end

  pipeline :browser do
    if Mix.env() == :prod do
      plug Plug.SSL, rewrite_on: [:x_forwarded_proto]
    end

    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    if Mix.env() == :prod do
      plug Plug.SSL, rewrite_on: [:x_forwarded_proto]
    end

    plug :accepts, ["json"]
  end

  pipeline :mix_common do
    plug LoadMix
    plug RedirectToPublishedMix
  end

  scope "/" do
    pipe_through :browser

    pow_routes()
    pow_extension_routes()

    if Mix.env() == :dev do
      forward "/sent-emails", Bamboo.SentEmailViewerPlug
    end
  end

  scope "/", MultiTrackListeningWeb do
    pipe_through :browser

    get "/", HomeController, :index

    get "/uploads/:uuid", StorageController, :serve_file

    post "/mixes/create", MixController, :create

    get "/confirm-email-intent/:id", CustomEmailConfirmationController, :show

    scope "/mixes" do
      pipe_through :mix_common

      get "/:id/track-one", MixController, :new_track_one
      post "/:id/track-one", MixController, :create_track_one
      get "/:id/track-two", MixController, :new_track_two
      post "/:id/track-two", MixController, :create_track_two
      get "/:id/parameters", MixController, :parameters
      put "/:id/parameters", MixController, :create_mix_render
      get "/:id/renders/:render_id", MixController, :mix_render
      post "/:id/renders/:render_id/publish", MixController, :publish
    end

    get "/published/:author_slug/:id", PublishedMixController, :show
  end

  scope "/", MultiTrackListeningWeb do
    pipe_through [:browser, :protected]

    get "/my-mixes", MyMixesController, :show
  end

  scope "/health", MultiTrackListeningWeb do
    get "/", HealthController, :index
  end
end

apps/multi_track_listening/lib/multi_track_listening_web/views/layout_view.ex
defmodule MultiTrackListeningWeb.LayoutView do
  use MultiTrackListeningWeb, :view

  defp path_segments(path) do
    String.split(path, "/", trim: true)
  end

  defp active_path?(conn, path, exact) do
    if exact do
      conn.path_info == path_segments(path)
    else
      List.starts_with?(conn.path_info, path_segments(path))
    end
  end

  defp navbar_classes(is_active) do
    if is_active do
      ["navbar-item", "is-active"]
    else
      ["navbar-item"]
    end
  end

  def navbar_link(conn, text, path, opts \\ []) do
    classes =
      active_path?(conn, path, Keyword.get(opts, :exact, false))
      |> navbar_classes()
      |> Enum.join(" ")

    link(text, Keyword.merge([to: path, class: classes], opts))
  end

  def notification_class("error") do
    "notification is-danger"
  end

  def notification_class("info") do
    "notification is-info"
  end

  def notification_class(_flash_key) do
    "notification"
  end
end

apps/multi_track_listening/lib/multi_track_listening_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Multi-Track Listening!</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-150925919-1"></script>
    <script>
      if(/multitracklistening\.net/.test(window.location.hostname)) {
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-150925919-1');
      }
    </script>
  </head>
  <body>
    <nav class="navbar is-dark" role="navigation">
      <div class="container">
        <div class="navbar-brand">
          <%= link "Multi-Track Listening!", to: Routes.home_path(@conn, :index),
            class: "navbar-item app-navbar-brand" %>
          <div class="navbar-item is-hidden-desktop">
            <%= form_tag Routes.mix_path(@conn, :create) do %>
              <%= submit "Create", class: "button is-primary" %>
            <% end %>
          </div>
        </div>
        <div class="navbar-menu">
          <div class="navbar-start">
            <%= navbar_link @conn, "Home", Routes.home_path(@conn, :index), exact: true %>
          </div>
          <div class="navbar-end is-hidden-touch">
            <div class="navbar-item">
              <%= form_tag Routes.mix_path(@conn, :create) do %>
                <%= submit "Create a Mix", class: "button is-primary" %>
              <% end %>
            </div>
            <%= if @current_user do %>
              <div class="navbar-item">Hello <%= @current_user.username %>!</div>
              <%= navbar_link @conn, "My Mixes", Routes.my_mixes_path(@conn, :show) %>
              <%= navbar_link @conn, "Sign Out", Routes.pow_session_path(@conn, :delete), method: :delete %>
            <% else %>
              <%= navbar_link @conn, "Sign In", Routes.pow_session_path(@conn, :new) %>
              <%= navbar_link @conn, "Sign Up", Routes.pow_registration_path(@conn, :new) %>
            <% end %>
          </div>
        </div>
      </div>
    </nav>
    <main role="main" class="app-main">
      <%= render @view_module, @view_template, assigns %>
    </main>
    <footer class="footer app-footer">
      <div class="content has-text-centered">
        <%= render "footer.html" %>
        <%= if Mix.env() == :dev do %>
          <a href="/sent-emails" target="blank" class="link">
            View local emails
          </a>
        <% end %>
      </div>
    </footer>
    <div class="app-notifications">
      <%= Enum.map(get_flash(@conn), fn {flash_key, flash_message} -> %>
        <%= if flash_message do %>
          <div class="<%= notification_class(flash_key) %>" data-is-notification="yes">
            <button class="delete" data-is-delete="yes"></button>
            <%= flash_message %>
          </div>
        <% end %>
      <% end) %>
    </div>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
    <%= render_existing @view_module, "scripts." <> @view_template, assigns %>
  </body>
</html>