apps/multi_track_listening/lib/multi_track_listening_web/router.ex
defmodule MultiTrackListeningWeb.Router do
  use MultiTrackListeningWeb, :router
  use Pow.Phoenix.Router
  use Pow.Extension.Phoenix.Router, otp_app: :multi_track_listening

  alias MultiTrackListeningWeb.Plugs.{RedirectToPublishedMix, LoadMix}

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler
  end

  pipeline :browser do
    if Mix.env() == :prod do
      plug Plug.SSL, rewrite_on: [:x_forwarded_proto]
    end

    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    if Mix.env() == :prod do
      plug Plug.SSL, rewrite_on: [:x_forwarded_proto]
    end

    plug :accepts, ["json"]
  end

  pipeline :mix_common do
    plug LoadMix
    plug RedirectToPublishedMix
  end

  scope "/" do
    pipe_through :browser

    pow_routes()
    pow_extension_routes()

    if Mix.env() == :dev do
      forward "/sent-emails", Bamboo.SentEmailViewerPlug
    end
  end

  scope "/", MultiTrackListeningWeb do
    pipe_through :browser

    get "/", HomeController, :index

    get "/uploads/:uuid", StorageController, :serve_file

    post "/mixes/create", MixController, :create

    get "/confirm-email-intent/:id", CustomEmailConfirmationController, :show

    scope "/mixes" do
      pipe_through :mix_common

      get "/:id/track-one", MixController, :new_track_one
      post "/:id/track-one", MixController, :create_track_one
      get "/:id/track-two", MixController, :new_track_two
      post "/:id/track-two", MixController, :create_track_two
      get "/:id/parameters", MixController, :parameters
      put "/:id/parameters", MixController, :create_mix_render
      get "/:id/renders/:render_id", MixController, :mix_render
      post "/:id/renders/:render_id/publish", MixController, :publish
    end

    get "/published/:author_slug/:id", PublishedMixController, :show
  end

  scope "/", MultiTrackListeningWeb do
    pipe_through [:browser, :protected]

    get "/my-mixes", MyMixesController, :show
  end

  scope "/health", MultiTrackListeningWeb do
    get "/", HealthController, :index
  end
end

apps/multi_track_listening/lib/mix/tasks/multi_track_listening/seed.ex
defmodule Mix.Tasks.MultiTrackListening.Seed do
  use Mix.Task
  alias MultiTrackListening.Repo
  alias MultiTrackListening.PublishedMixes.PublishedMix

  def run(_) do
    Mix.Task.run("app.start", [])
    seed(Mix.env())
  end

  def seed(:dev) do
    Repo.insert!(%PublishedMix{
      audio_file: "c05a05c6-80dd-4bc2-9ca1-4fd7ff7ce8c5",
      track_one_name: "Can't Feel My Face",
      track_two_name: "Regret"
    })

    Repo.insert!(%PublishedMix{
      audio_file: "8ec07f03-f3fb-42e8-93bf-108d9bb44fb1",
      track_one_name: "Gas Gas Gas",
      track_two_name: "Running In The 90s"
    })
  end

  def seed(:prod), do: nil
end

apps/multi_track_listening/lib/multi_track_listening/mixes/mix.ex
defmodule MultiTrackListening.Mixes.Mix do
  use Ecto.Schema
  import Ecto.Changeset
  alias MultiTrackListening.Mixes.{Track, MixParameters}
  alias MultiTrackListening.PublishedMixes.PublishedMix

  @type t :: %__MODULE__{
          id: integer,
          track_one: Track.t(),
          track_two: Track.t(),
          parameters: MixParameters.t(),
          published_mix_id: integer,
          published_mix: PublishedMix.t() | Ecto.Association.NotLoaded.t(),
          inserted_at: DateTime.t(),
          updated_at: DateTime.t()
        }

  schema "mixes" do
    embeds_one :track_one, Track, on_replace: :delete
    embeds_one :track_two, Track, on_replace: :delete

    has_one :parameters, MixParameters, on_replace: :update

    belongs_to :published_mix, PublishedMix

    timestamps()
  end

  @spec is_published(t()) :: boolean()
  def is_published(mix = %__MODULE__{}), do: not is_nil(mix.published_mix_id)

  @doc false
  def changeset(mix, attrs) do
    mix
    |> cast(attrs, [])
    |> cast_assoc(:parameters, with: &MixParameters.changeset/2)
    |> cast_embed(:track_one, with: &Track.changeset/2)
    |> cast_embed(:track_two, with: &Track.changeset/2)
  end
end

apps/multi_track_listening/lib/multi_track_listening/mixes/mix_parameters.ex
defmodule MultiTrackListening.Mixes.MixParameters do
  use Ecto.Schema
  import Ecto.Changeset

  alias MultiTrackListening.Mixes.Mix

  @type t :: %__MODULE__{
          id: integer,
          mix_duration: integer,
          track_one_start: integer,
          track_two_start: integer,
          track_one_gain: float,
          track_two_gain: float,
          drifting_speed: float,
          mix_id: integer,
          mix: Mix.t(),
          inserted_at: DateTime.t(),
          updated_at: DateTime.t()
        }

  schema "mix_parameters" do
    field :mix_duration, :integer, default: 60
    field :track_one_start, :integer, default: 0
    field :track_two_start, :integer, default: 0
    field :track_one_gain, :float, default: 1.0
    field :track_two_gain, :float, default: 1.0
    field :drifting_speed, :float, default: 6.0

    belongs_to :mix, Mix

    timestamps()
  end

  @doc false
  def changeset(mix_parameters, attrs) do
    mix_parameters
    |> cast(attrs, [:track_one_start, :track_two_start, :mix_duration, :drifting_speed, :track_one_gain, :track_two_gain])
    |> validate_number(:track_one_start, greater_than_or_equal_to: 0)
    |> validate_number(:track_two_start, greater_than_or_equal_to: 0)
    |> validate_number(:mix_duration, greater_than_or_equal_to: 5)
    |> validate_number(:mix_duration, less_than_or_equal_to: 90)
    |> validate_number(:drifting_speed, greater_than_or_equal_to: 0, less_than_or_equal_to: 11)
    |> validate_number(:track_one_gain, greater_than_or_equal_to: 0, less_than_or_equal_to: 1.0)
    |> validate_number(:track_two_gain, greater_than_or_equal_to: 0, less_than_or_equal_to: 1.0)
    |> validate_required([:track_one_start, :track_two_start, :mix_duration])
  end
end

apps/multi_track_listening/lib/multi_track_listening/mixes/mixes.ex
defmodule MultiTrackListening.Mixes do
  @moduledoc """
  The Mixes context.
  """

  import Ecto.Query, warn: false
  alias MultiTrackListening.Repo
  alias MultiTrackListening.Storage
  alias MultiTrackListening.PublishedMixes
  alias MultiTrackListening.Mixes.{Mix, TrackUpload, Track, Render}

  @doc """
  Gets a single mix.

  Raises `Ecto.NoResultsError` if the Mix does not exist.

  ## Examples

      iex> get_mix!(123)
      %Mix{}

      iex> get_mix!(456)
      ** (Ecto.NoResultsError)

  """
  def get_mix!(id), do: Repo.get!(Mix, id) |> Repo.preload(:parameters)

  @doc """
  Creates a mix.

  ## Examples

      iex> create_mix(%{field: value})
      {:ok, %Mix{}}

      iex> create_mix(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_mix(attrs \\ %{}) do
    %Mix{}
    |> Mix.changeset(attrs)
    |> Repo.insert()
  end

  @spec create_mix_default!() :: Ecto.Schema.t()
  def create_mix_default!() do
    Repo.insert!(%Mix{})
  end

  @doc """
  Updates a mix.

  ## Examples

      iex> update_mix(mix, %{field: new_value})
      {:ok, %Mix{}}

      iex> update_mix(mix, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_mix(%Mix{} = mix, attrs) do
    mix
    |> Mix.changeset(attrs)
    |> Repo.update()
  end

  def create_render(%Mix{parameters: parameters} = mix) do
    track_one_file = Storage.duplicate_file!(mix.track_one.file_uuid)
    track_two_file = Storage.duplicate_file!(mix.track_two.file_uuid)

    render =
      Repo.insert!(%Render{
        mix: mix,
        track_one_file_uuid: track_one_file,
        track_two_file_uuid: track_two_file,
        drifting_speed: parameters.drifting_speed,
        mix_duration: parameters.mix_duration,
        track_one_start: parameters.track_one_start,
        track_two_start: parameters.track_two_start,
        track_one_name: mix.track_one.name,
        track_two_name: mix.track_two.name,
        track_one_gain: parameters.track_one_gain,
        track_two_gain: parameters.track_two_gain
      })

    Honeydew.async({:do_render, [render]}, :mix_render_queue)

    render
  end

  @spec get_render!(integer) :: Render.t()
  def get_render!(render_id) do
    Repo.get!(Render, render_id) |> Repo.preload(:mix)
  end

  @spec get_mix_render!(integer, integer) :: Render.t()
  def get_mix_render!(mix_id, render_id) do
    Repo.get_by!(Render, mix_id: mix_id, id: render_id) |> Repo.preload(:mix)
  end

  @spec update_render_internal(Render.t(), keyword() | %{optional(atom()) => any()}) :: Render.t()
  def update_render_internal(render, updates) do
    Ecto.Changeset.change(render, updates) |> Repo.update!() |> Repo.preload(:mix)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking mix changes.

  ## Examples

      iex> change_mix(mix)
      %Ecto.Changeset{source: %Mix{}}

  """
  def change_mix(%Mix{} = mix) do
    Mix.changeset(mix, %{})
  end

  defp persist_track_upload(attrs) do
    case TrackUpload.changeset(%TrackUpload{}, attrs) |> Ecto.Changeset.apply_action(:insert) do
      result = {:error, %Ecto.Changeset{}} ->
        result

      {:ok, %TrackUpload{file: file, name: name, client_uuid: client_uuid}} ->
        uuid = Storage.upload_file!(file.path, file.content_type)
        {:ok, %Track{file_uuid: uuid, name: name, client_uuid: client_uuid}}
    end
  end

  @spec change_track_upload() :: Ecto.Changeset.t()
  def change_track_upload() do
    TrackUpload.changeset(%TrackUpload{}, %{})
  end

  @spec attach_track_one(Mix.t(), any()) :: {:ok, Mix.t()} | {:error, Ecto.Changeset.t()}
  def attach_track_one(mix = %Mix{}, track_upload) do
    with {:ok, track} <- persist_track_upload(track_upload) do
      updated = Repo.update!(Ecto.Changeset.change(mix, track_one: track))

      if not is_nil(mix.track_one) do
        Storage.delete_file!(mix.track_one.file_uuid)
      end

      {:ok, updated}
    end
  end

  @spec attach_track_two(Mix.t(), any()) :: {:ok, Mix.t()} | {:error, Ecto.Changeset.t()}
  def attach_track_two(mix, track_upload) do
    with {:ok, track} <- persist_track_upload(track_upload) do
      updated = Repo.update!(Ecto.Changeset.change(mix, track_two: track))

      if not is_nil(mix.track_two) do
        Storage.delete_file!(mix.track_two.file_uuid)
      end

      {:ok, updated}
    end
  end

  @spec publish_mix(Render.t()) :: PublishedMix.t()
  def publish_mix(render = %Render{mix: mix, result_file_uuid: result_file}, author \\ nil)
      when is_binary(result_file) do
    PublishedMixes.create_published_mix_internal(
      audio_file: Storage.duplicate_file!(result_file),
      track_one_name: render.track_one_name,
      track_two_name: render.track_two_name,
      mix: mix,
      render: render,
      author: author
    )
  end
end

apps/multi_track_listening/lib/multi_track_listening/mixes/render.ex
defmodule MultiTrackListening.Mixes.Render do
  use Ecto.Schema
  import EctoEnum

  alias MultiTrackListening.Mixes.Mix
  alias MultiTrackListening.PublishedMixes.PublishedMix

  defenum(StatusEnum, requested: 0, in_progress: 1, finished: 2, error: 3, canceled: 4, aborted: 5)

  @type t :: %__MODULE__{
          id: integer,
          track_one_file_uuid: String.t(),
          track_two_file_uuid: String.t(),
          result_file_uuid: String.t(),
          mix_duration: integer,
          track_one_start: integer,
          track_two_start: integer,
          track_one_gain: float,
          track_two_gain: float,
          drifting_speed: float,
          track_one_name: String.t(),
          track_two_name: String.t(),
          status: :requested | :in_progress | :finished | :error | :canceled | :aborted,
          mix_id: integer,
          mix: Mix.t(),
          published_mix: PublishedMix.t() | Ecto.Association.NotLoaded.t(),
          inserted_at: DateTime.t(),
          updated_at: DateTime.t()
        }

  def is_canceled(render) do
    render.status == :canceled || render.status == :aborted
  end

  schema "mix_renders" do
    field :track_one_file_uuid, :string
    field :track_two_file_uuid, :string
    field :result_file_uuid, :string

    field :mix_duration, :integer
    field :track_one_start, :integer
    field :track_two_start, :integer
    field :drifting_speed, :float

    field :track_one_gain, :float
    field :track_two_gain, :float

    field :track_one_name, :string
    field :track_two_name, :string

    field :status, StatusEnum, default: :requested

    belongs_to :mix, Mix
    belongs_to :published_mix, PublishedMix

    timestamps()
  end
end

apps/multi_track_listening/lib/multi_track_listening/mixes/track.ex
defmodule MultiTrackListening.Mixes.Track do
  use Ecto.Schema
  import Ecto.Changeset

  alias MultiTrackListening.Storage

  @type t :: %__MODULE__{
          name: String.t(),
          client_uuid: String.t(),
          file_uuid: Storage.FileId.t()
        }

  embedded_schema do
    field(:name, :string)
    field(:client_uuid, :string)
    field(:file_uuid, :string)
  end

  @doc false
  def changeset(track, attrs) do
    track
    |> cast(attrs, [:name, :client_uuid, :file_uuid])
    |> validate_required([:name, :file_uuid])
  end
end

apps/multi_track_listening/lib/multi_track_listening_web/controllers/mix_controller.ex
defmodule MultiTrackListeningWeb.MixController do
  use MultiTrackListeningWeb, :controller

  alias MultiTrackListening.{Mixes, Storage}
  alias MultiTrackListening.PublishedMixes.PublishedMix

  def create(conn, _params) do
    mix = Mixes.create_mix_default!()
    redirect(conn, to: Routes.mix_path(conn, :new_track_one, mix))
  end

  def new_track_one(conn, _params) do
    mix = conn.assigns[:mix]
    changeset = Mixes.change_track_upload()
    render(conn, "track-one.html", mix: mix, changeset: changeset)
  end

  def create_track_one(conn, %{"track_upload" => params}) do
    mix = conn.assigns[:mix]

    case Mixes.attach_track_one(mix, params) do
      {:ok, updated} ->
        redirect(conn, to: Routes.mix_path(conn, :parameters, updated))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "track-one.html", mix: mix, changeset: changeset)
    end
  end

  def new_track_two(conn, _params) do
    mix = conn.assigns[:mix]
    changeset = Mixes.change_track_upload()
    render(conn, "track-two.html", mix: mix, changeset: changeset)
  end

  def create_track_two(conn, %{"track_upload" => params}) do
    mix = conn.assigns[:mix]

    case Mixes.attach_track_two(mix, params) do
      {:ok, updated} ->
        redirect(conn, to: Routes.mix_path(conn, :parameters, updated))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "track-two.html", mix: mix, changeset: changeset)
    end
  end

  def parameters(conn, _params) do
    mix = conn.assigns[:mix]
    changeset = Mixes.change_mix(mix)

    cond do
      is_nil(mix.track_one) ->
        redirect(conn, to: Routes.mix_path(conn, :new_track_one, mix))

      is_nil(mix.track_two) ->
        redirect(conn, to: Routes.mix_path(conn, :new_track_two, mix))

      true ->
        render(conn, "parameters.html",
          mix: mix,
          changeset: changeset,
          track_one_url: Storage.file_url(mix.track_one.file_uuid),
          track_two_url: Storage.file_url(mix.track_two.file_uuid)
        )
    end
  end

  def create_mix_render(conn, %{"mix" => params}) do
    mix = conn.assigns[:mix]

    with {:ok, mix} <- Mixes.update_mix(mix, params) do
      mix_render = Mixes.create_render(mix)
      redirect(conn, to: Routes.mix_path(conn, :mix_render, mix.id, mix_render.id))
    else
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "parameters.html", mix: mix, changeset: changeset)
    end
  end

  def mix_render(conn, %{"render_id" => render_id}) do
    mix = conn.assigns[:mix]
    mix_render = Mixes.get_mix_render!(mix.id, render_id)
    render(conn, "mix-render.html", mix: mix, mix_render: mix_render)
  end

  def publish(conn, %{"render_id" => render_id}) do
    mix = conn.assigns[:mix]
    mix_render = Mixes.get_mix_render!(mix.id, render_id)
    author = Pow.Plug.current_user(conn)
    published = Mixes.publish_mix(mix_render, author)

    redirect(conn,
      to:
        Routes.published_mix_path(
          conn,
          :show,
          PublishedMix.author_slug(published),
          published
        )
    )
  end
end

apps/multi_track_listening/lib/multi_track_listening_web/views/mix_view.ex
defmodule MultiTrackListeningWeb.MixView do
  use MultiTrackListeningWeb, :view

  alias MultiTrackListening.Storage

  def render("scripts.track-one.html", assigns) do
    render_script_tag(assigns.conn, "track-upload.js")
  end

  def render("scripts.track-two.html", assigns) do
    render_script_tag(assigns.conn, "track-upload.js")
  end

  def render("scripts.parameters.html", assigns) do
    render_script_tag(assigns.conn, "mix-parameters.js")
  end

  def render("scripts.mix-render.html", assigns) do
    render_script_tag(assigns.conn, "mix-render.js")
  end

  def render("mix-render.json", %{mix_render: mix_render}) do
    %{
      status: mix_render.status,
      status_text: display_mix_render_status(mix_render.status),
      result_url: mix_render_result_url(mix_render)
    }
  end

  def mix_render_result_url(mix_render) do
    if mix_render.result_file_uuid do
      Storage.file_url(mix_render.result_file_uuid)
    end
  end

  def display_mix_render_status(render_status) do
    %{
      finished: "Done! You can now publish or download the mix.",
      error: "There was an error rendering this mix. Please try again later."
    }[render_status]
  end
end

apps/multi_track_listening/lib/multi_track_listening_web/templates/mix/finalize.html.eex
<section class="section finalize-mix">
  <div class="container">
    <h1 class="title">Finalize Mix</h1>

    <h2 class="subtitle">
      Mixing
      <%= content_tag :i, @mix.track_one.name %>
      and
      <%= content_tag :i, @mix.track_two.name %>
    </h2>

    <%= form_for @changeset, Routes.mix_path(@conn, :create_mix_render, @mix), [id: "finalize_mix_form"], fn f -> %>

      <div class="field is-grouped">
        <div class="control">
          <%= link "Change Track One", to: Routes.mix_path(@conn, :new_track_one, @mix),
            class: "is-link" %>
        </div>

        <div class="control">
          <%= link "Change Track Two", to: Routes.mix_path(@conn, :new_track_two, @mix),
            class: "is-link" %>
        </div>
      </div>

      <%= inputs_for f, :parameters, fn pf -> %>
        <div class="field">
          <%= label pf, :track_one_start, class: "label" %>
          <div class="field-body">
            <div class="control">
              <%= number_input pf, :track_one_start, class: "input", step: 1, min: 0 %>
            </div>
          </div>
          <%= error_tag pf, :track_one_start %>
        </div>

        <div class="field">
          <%= label pf, :track_two_start, class: "label" %>
          <div class="field-body">
            <div class="control">
              <%= number_input pf, :track_two_start, class: "input", step: 1, min: 0 %>
            </div>
          </div>
          <%= error_tag pf, :track_two_start %>
        </div>

        <div class="field">
          <%= label pf, :mix_duration, class: "label" %>
          <div class="field-body">
            <div class="control">
              <%= number_input pf, :mix_duration, class: "input", step: 1, min: 5, max: 90 %>
            </div>
          </div>
          <%= error_tag pf, :mix_duration %>
        </div>
      <% end %>

      <div class="field is-grouped">
        <div class="control">
          <%# Since this button is declared earlier in markup, client-side preview will
              be the default submit action. %>      
          <%= submit "Preview", class: "button is-primary", id: "preview_button",
            data: [
              track_one_client_uuid: @mix.track_one.client_uuid,
              track_two_client_uuid: @mix.track_two.client_uuid,
              track_one_url: Routes.storage_url(@conn, :serve_file, @mix.track_one.file_uuid),
              track_two_url: Routes.storage_url(@conn, :serve_file, @mix.track_two.file_uuid)
            ] %>
          <span id="preview_error" class="help is-danger is-hidden"></span>
        </div>
        <div class="control">
          <%= content_tag :button, "Stop Preview", class: "button is-secondary",
            id: "stop_preview_button", disabled: true %>
        </div>
      </div>

      <p class="finalize-mix__description">Once you're happy with the preview, render it so you can share or download the result.</p>

      <%= submit "Render", class: "button is-danger" %>

    <% end %>
  </div>
</section>

apps/multi_track_listening/lib/multi_track_listening_web/templates/mix/mix-render.html.eex
<section class="section">
  <div class="container">
    <h1 class="title">Rendering Mix</h1>

    <nav class="breadcrumb has-arrow-separator" aria-label="breadcrumbs">
      <ul>
        <li>
          <%= link "Track One", to: Routes.mix_path(@conn, :new_track_one, @mix) %>
        </li>
        <li>
          <%= link "Track Two", to: Routes.mix_path(@conn, :new_track_two, @mix) %>
        </li>
        <li>
          <%= link "Parameters", to: Routes.mix_path(@conn, :parameters, @mix) %>
        </li>
        <li>
          <%= link "Render", to: Routes.mix_path(@conn, :mix_render, @mix, @mix_render) %>
        </li>
      </ul>
    </nav>

    <p class="form-description">
      Rendering mix with <%= content_tag :i, @mix.track_one.name %>
      and
      <%= content_tag :i, @mix.track_two.name %>.
    </p>

    <%= if @mix_render.status != :finished && @mix_render.status != :error do %>
      <noscript>
        <p class="form-description">Please refresh your browser to update mix status.</p>
      </noscript>
    <% end %>

    <%= case @mix_render.status do %>
      <% :finished -> %>
        <progress id="render_progress" class="progress is-success mix-render-progress" 
          value="100" max="100">
          100%
        </progress>
      <% :error -> %>
        <progress id="render_progress" class="progress is-danger mix-render-progress"
          value="15" max="100">
          15%
        </progress>
      <% _ -> %>
        <progress id="render_progress" class="progress is-primary mix-render-progress" max="100">
          0%
        </progress>
    <% end %>

    <%= if @mix_render.status == :error do %>
      <p id="render_status" class="form-description has-text-danger">
        <%= display_mix_render_status @mix_render.status %>
      </p>
    <% else %>
      <p id="render_status" class="form-description">
        <%= display_mix_render_status @mix_render.status %>
      </p>
    <% end %>

    <%= content_tag :audio, nil,
      id: "result_audio",
      class: (
        if @mix_render.status == :finished do
          "mix-render-audio"
        else
          "mix-render-audio is-hidden"
        end
      ),
      controls: true,
      src: mix_render_result_url(@mix_render) %>

    
    <%= content_tag :div, id: "finished_footer", class: (
        if @mix_render.status == :finished do
          ""
        else
          "is-hidden"
        end
      ) do %>
      <div class="field is-grouped">
        <div class="control">
          <%= form_tag Routes.mix_path(@conn, :publish, @mix.id, @mix_render.id),
              id: "publish_form" do %>
            <% publish_text = if @current_user, do: "Publish", else: "Publish Anonymously" %>
            <% confirm_text = if @current_user, do: "Finalize and publish this mix?", else: "Finalize this mix and publish anonymously?" %>

            <%= submit publish_text,
              class: "button is-primary", id: "publish_button",
              data: [
                confirm: confirm_text,
                track_one_client_uuid: @mix.track_one.client_uuid,
                track_two_client_uuid: @mix.track_two.client_uuid
              ] %>
          <% end %>
        </div>

        <div class="control">
          <%= link "Download", to: mix_render_result_url(@mix_render) || "", download: true,
            class: "button is-secondary", id: "download_button" %>
        </div>
      </div>

      <%= unless @current_user do %>
        <% intent_url = @conn.request_path %>
        <p class="form-description">
          You can also
          <%= link "Sign In", to: Routes.pow_session_path(@conn, :new, intent: intent_url) %>
          or
          <%= link "Sign Up", to: Routes.pow_registration_path(@conn, :new, intent: intent_url) %>          
          to publish this mix under your account.
        </p>
      <% end %>

    <% end %>
  </div>
</section>

apps/multi_track_listening/lib/multi_track_listening_web/templates/mix/track-one.html.eex
<section class="section">  
  <div class="container">
    <h1 class="title">New Mix</h1>

    <nav class="breadcrumb has-arrow-separator" aria-label="breadcrumbs">
      <ul>
        <li>
          <%= link "Track One", to: Routes.mix_path(@conn, :new_track_one, @mix) %>
        </li>
      </ul>
    </nav>


    <p class="form-description">Please choose an MP3 file from your computer.</p>

    <%= render "track-upload-form.html", Map.merge(assigns,
      %{ action: Routes.mix_path(@conn, :create_track_one, @mix), track: @mix.track_one }) %>
  </div>
</section>

apps/multi_track_listening/lib/multi_track_listening_web/templates/mix/track-two.html.eex
<section class="section">  
  <div class="container">
    <h1 class="title">New Mix</h1>

    <nav class="breadcrumb has-arrow-separator" aria-label="breadcrumbs">
      <ul>
        <li>
          <%= link "Track One", to: Routes.mix_path(@conn, :new_track_one, @mix) %>
        </li>
        <li>
          <%= link "Track Two", to: Routes.mix_path(@conn, :new_track_two, @mix) %>
        </li>
      </ul>
    </nav>

    <p class="form-description">Upload another file for multi-track listening!</p>

    <%= render "track-upload-form.html", Map.merge(assigns,
      %{ action: Routes.mix_path(@conn, :create_track_two, @mix), track: @mix.track_two }) %>
  </div>
</section>

apps/multi_track_listening/lib/multi_track_listening_web/templates/mix/track-upload-form.html.eex
<%= form_for @changeset, @action,
  [multipart: true, method: :post, id: "track_upload_form", class: "track-upload-form"],
  fn f -> %>

  <div class="field">
    <%= label f, :file, class: "label" %>
    <div class="file" id="file_input_root">
      <label class="file-label">
        <%= file_input f, :file, required: true, accept: ".mp3", class: "file-input" %>
        <span class="file-cta">
          <span class="file-icon">
            <i class="fa fa-upload"></i>
          </span>

          <span class="file-label">
            Choose a file…
          </span>
        </span>
        <span id="pseudo_file_name" class="file-name is-hidden"></span>
      </label>
    </div>
    <%= error_tag f, :file %>
  </div>

  <%= text_field f, :name, "Song name", required: true %>

  <%= if @track do %>
    <%= hidden_input f, :client_uuid, value: @track.client_uuid %>
  <% else %>
    <%= hidden_input f, :client_uuid %>
  <% end %>

  <div class="field">
    <div class="field-body">
      <div class="control">
        <%= submit "Upload", id: "track_upload_submit", class: "button is-primary" %>
      </div>
    </div>
  </div>
<% end %>